service:
  name: web-crawler-lambda

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  get-site-map:
    handler: src/handler.getSiteMap
    events:
      - http:
          method: get
          path: get-site-map

custom:
  webpack:
    includeModules: true
